#!/bin/bash
set -e # stop execution if a command or pipeline has an error
set -x # print statements as they're being executed

docker run -p 5000:5000 --platform=linux/amd64 r8.im/zeke/haiku-progressive-image