name: Test

on:
  push:
  pull_request:

jobs:
  test:
    name: Python tests
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.12'
        run:
      
      - name: Install pytest
      - run: python my_script.py

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Checkout Cog repo
        uses: actions/checkout@v2
        with:
          repository: replicate/cog
          # ref: 'future'
          path: cog

      - name: Run tests
        run: script/test